### ISSUE TITLE
function findController have a problem

### ISSUE THREAD

**Issue by ferrywon** [kookxiang/KK-Framework#2]
if url is `http://***.com/***.php`

when code run here

if (is_dir(LIBRARY_PATH . "Controller/{$subDir}{$controller}")) {
...
}
} elseif (file_exists(LIBRARY_PATH . "Controller/{$subDir}{$controller}.php")) {
...
}

they are both false!

Is deliberately? or Re-write rules?

**Comment by kookxiang** [comment]
If the file is exists, it would run before triggering rewrite engine, and the code will not reach `index.php` and the entire framework.
